/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplikasi;
   
import app.db.Mahasiswa;
import app.db.MahasiswaManager;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class JendelaUtama extends javax.swing.JFrame {
    List<Mahasiswa> mahasiswa = new ArrayList<Mahasiswa>();
    int currentRow = 0;

    /**
     * Creates new form JendelaUtama
     */
    public JendelaUtama() {
        String lookAndFeel = javax.swing.UIManager.getSystemLookAndFeelClassName();
        try {
            javax.swing.UIManager.setLookAndFeel(lookAndFeel);           
        }catch (Exception e) {
        
        }
        initComponents();
            loadData();
            binData();
            this.setTitle("Data Mahasiswa");
            txtNo_BP.setEditable(false);
            txtNama.setEditable(false);
            txtTempat_Lahir.setEditable(false);
            txtTanggal_Lahir.setEditable(false);
            txtAlamat.setEditable(false);
            txtTelp.setEditable(false);
            txtAsal_Sekolah.setEditable(false);
            this.setLocationRelativeTo(this);
    }

    private void loadData(){
        MahasiswaManager mhsmgr = new MahasiswaManager();
        mahasiswa = mhsmgr.getMahasiswa();
        mhsmgr.closeConnection();
    }
    
    private void binData(){
        if (mahasiswa.size()>0){
            Mahasiswa m = mahasiswa.get(currentRow);
            txtNo_BP.setText(m.getnobp());
            txtNama.setText(m.getnama());
            txtTempat_Lahir.setText(m.gettmplahir());
            txtTanggal_Lahir.setText(m.gettgllahir());
            txtAlamat.setText(m.getalamat());
            txtTelp.setText(m.gettlp());
            txtAsal_Sekolah.setText(m.getasalsekolah());
        } else {
            currentRow = 0;
            txtNo_BP.setText("");
            txtNama.setText("");
            txtTempat_Lahir.setText("");
            txtTanggal_Lahir.setText("");
            txtAlamat.setText("");
            txtTelp.setText("");
            txtAsal_Sekolah.setText("");
            }
    }    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNo_BP = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtTempat_Lahir = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTanggal_Lahir = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTelp = new javax.swing.JTextField();
        txtAsal_Sekolah = new javax.swing.JTextField();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Mahasiswa"));

        jLabel1.setText("No BP");

        jLabel2.setText("Nama");

        jLabel3.setText("Tempat/Tgl Lahir");

        txtNo_BP.setText("jTextField1");

        txtNama.setText("jTextField2");

        txtTempat_Lahir.setText("jTextField3");

        jLabel4.setText("/");

        txtTanggal_Lahir.setText("jTextField4");

        jLabel5.setText("Alamat");

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        jLabel6.setText("No Telphone");

        jLabel7.setText("Asal Sekolah");

        txtTelp.setText("jTextField5");

        txtAsal_Sekolah.setText("jTextField6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNo_BP, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtAsal_Sekolah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addComponent(txtTelp, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTempat_Lahir, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(txtNama))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTanggal_Lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNo_BP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtTempat_Lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtTanggal_Lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAsal_Sekolah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        btnPrev.setText("<<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnNew.setText("Baru");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Hapus");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrev)
                .addGap(18, 18, 18)
                .addComponent(btnNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(btnNew)
                .addGap(27, 27, 27)
                .addComponent(btnEdit)
                .addGap(27, 27, 27)
                .addComponent(btnDelete)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrev)
                    .addComponent(btnNext)
                    .addComponent(btnNew)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (btnDelete.getText().equals("Delete")) {
            int dialog = JOptionPane.showConfirmDialog(this, "Apakah Anda Yakin Akan Menghapus Data Ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            MahasiswaManager mhsmgr = new MahasiswaManager();
            Mahasiswa m = mahasiswa.get(currentRow);
                if (dialog == JOptionPane.YES_NO_OPTION) {
                    if (mhsmgr.Delete(m)>0){
                        loadData();
                        currentRow = currentRow - 1;
                        binData();
                        JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus","Informasi", JOptionPane.INFORMATION_MESSAGE);

                } else {
                    JOptionPane.showMessageDialog(this, "Data Gagal Dihapus","Informasi", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            } else if (btnDelete.getText().equals("Batal")) {
                loadData();
                binData();
                btnNew.setText("Baru");
                btnEdit.setText("Ubah");
                btnDelete.setText("Hapus");
                btnEdit.setEnabled(true);
                btnNew.setEnabled(true);
                btnPrev.setEnabled(true);
                btnNext.setEnabled(true);
                txtNo_BP.setEditable(false);
                txtNama.setEditable(false);
                txtTempat_Lahir.setEditable(false);
                txtTanggal_Lahir.setEditable(false);
                txtAlamat.setEditable(false);
                txtTelp.setEditable(false);
                txtAsal_Sekolah.setEditable(false);
            }
// TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        if(btnNew.getText().equals("New")){
            txtNo_BP.setText("");
            txtNama.setText("");
            txtTempat_Lahir.setText("");
            txtTanggal_Lahir.setText("");
            txtAlamat.setText("");
            txtTelp.setText("");
            txtAsal_Sekolah.setText("");
            txtNo_BP.setEditable(true);
            txtNama.setEditable(true);
            txtTempat_Lahir.setEditable(true);
            txtTanggal_Lahir.setEditable(true);
            txtAlamat.setEditable(true);
            txtTelp.setEditable(true);
            txtAsal_Sekolah.setEditable(true);
            txtNo_BP.requestFocus();
            btnNew.setText("Simpan");
            btnDelete.setText("Batal");
            btnEdit.setEnabled(false);
            btnPrev.setEnabled(false);
            btnNext.setEnabled(false);
            }else {
                if (!txtNo_BP.getText().equals("") && !txtNama.getText().equals("")){
                    MahasiswaManager mhsmgr = new MahasiswaManager();
                    Mahasiswa m = new Mahasiswa();
                    m.setnobp( txtNo_BP.getText());
                    m.setnama(txtNama.getName());
                    m.settmplahir(txtTempat_Lahir.getText());
                    m.settgllahir(txtTanggal_Lahir.getText());
                    m.setalamat(txtAlamat.getText());
                    m.settlp(txtTelp.getText());
                    m.setasalsekolah(txtAsal_Sekolah.getText());
                    if (mhsmgr.Insert(m)>0) {
                        loadData();
                        currentRow = mahasiswa.size()-1;
                        binData();
                        JOptionPane.showMessageDialog(this,"Data Berhasil Disimpan","Informasi",JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this,"Data Gagal Disimpan","Informasi", JOptionPane.INFORMATION_MESSAGE);
                    }
                    txtNo_BP.setEditable(false);
                    txtNama.setEditable(false);
                    txtTempat_Lahir.setEditable(false);
                    txtTanggal_Lahir.setEditable(false);
                    txtAlamat.setEditable(false);
                    txtTelp.setEditable(false);
                    txtAsal_Sekolah.setEditable(false);
                    btnNew.setText("New");
                    btnDelete.setText("Delete");
                    btnEdit.setEnabled(true);
                    btnPrev.setEnabled(true);
                    btnNext.setEnabled(true);
                    mhsmgr.closeConnection();
            } else {
                JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan","Informasi", JOptionPane.INFORMATION_MESSAGE);
}
}
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (btnEdit.getText().equals("Edit")){
            txtNo_BP.setText("");
            txtNama.setText("");
            txtTempat_Lahir.setText("");
            txtTanggal_Lahir.setText("");
            txtAlamat.setText("");
            txtTelp.setText("");
            txtAsal_Sekolah.setText("");
            txtNo_BP.setEditable(true);
            txtNama.setEditable(true);
            txtTempat_Lahir.setEditable(true);
            txtTanggal_Lahir.setEditable(true);
            txtAlamat.setEditable(true);
            txtTelp.setEditable(true);
            txtAsal_Sekolah.setEditable(true);
            txtNo_BP.requestFocus();
            btnNew.setText("Simpan");
            btnDelete.setText("Batal");
            btnEdit.setEnabled(false);
            btnPrev.setEnabled(false);
            btnNext.setEnabled(false);
        } else {
            MahasiswaManager mhsmgr = new MahasiswaManager();
            Mahasiswa m = new Mahasiswa();
            m.setnobp(txtNo_BP.getText());
            m.setnama(txtNama.getName());
            m.settmplahir(txtTempat_Lahir.getText());
            m.settgllahir(txtTanggal_Lahir.getText());
            m.setalamat(txtAlamat.getText());
            m.settlp(txtTelp.getText());
            m.setasalsekolah(txtAsal_Sekolah.getText());
                if (mhsmgr.Update(m)>0){
                    loadData();
                    binData();
                    JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan","Informasi", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this, "Data Gagal Disimpan","Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
            txtNo_BP.setEditable(false);
            txtNama.setEditable(false);
            txtTempat_Lahir.setEditable(false);
            txtTanggal_Lahir.setEditable(false);
            txtAlamat.setEditable(false);
            txtTelp.setEditable(false);
            txtAsal_Sekolah.setEditable(false);
            btnNew.setText("Baru");
            btnDelete.setText("Hapus");
            btnPrev.setEnabled(true);
            btnNext.setEnabled(true);
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        if (currentRow < mahasiswa.size()-1){
            ++currentRow;
            btnPrev.setEnabled(true);
            }else {
            btnNext.setEnabled(false);
            }
            binData();

// TODO add your handling code here:
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (currentRow < mahasiswa.size()-1){
            --currentRow;
            btnPrev.setEnabled(true);
            }else{
            btnNext.setEnabled(false);
            }
            binData();       
// TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JendelaUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JendelaUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JendelaUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JendelaUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JendelaUtama().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtAsal_Sekolah;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNo_BP;
    private javax.swing.JTextField txtTanggal_Lahir;
    private javax.swing.JTextField txtTelp;
    private javax.swing.JTextField txtTempat_Lahir;
    // End of variables declaration//GEN-END:variables
}


